Add protonation modification ASPprot, GLUprot, HISprot1 and HISprot2 …
MRC-LMB-ComputationalStructuralBiology/monomers pull request #59
Opened 2024-11-25 18:04 UTC by LucreziaCatapano

…in `mon_lib_list.cif`

2024-11-25 22:02 UTC, keitaroyam commented
Did you do any test (hydrogen generation, refinement etc) using this?

Please update links_and_mods.cif as well, by doing
```
sed -n '/^data_link_list/,$p' list/mon_lib_list.cif > links_and_mods.cif
```
See #49 for details.

2024-11-30 13:01 UTC, keitaroyam requested changes
I think modifications should be minimum. Please see specific comments.
(Changes should be made in list/mon_lib_list.cif and then copied to links_and_mods.cif)

2024-11-30 13:01 UTC, keitaroyam commented on links_and_mods.cif
> +ASPprot change O C CA N sp2_sp3_1 0.000 20.0 6
These changes are irrelevant and may be removed.

2024-11-30 13:01 UTC, keitaroyam commented on links_and_mods.cif
> +GLUprot change O C CA N sp2_sp3_1 0.000 20.0 6
These changes are unnecessary

2024-11-30 13:01 UTC, keitaroyam commented on links_and_mods.cif
> +
unnecessary changes

2024-11-30 13:01 UTC, keitaroyam commented on links_and_mods.cif
> +
unnecessary changes

2025-02-11 15:04 UTC, GaribMurshudov commented
Has anybody tested this?

2025-02-11 15:21 UTC, LucreziaCatapano commented
I did for neutron.

Sent from my iPhone

> On 11 Feb 2025, at 15:04, GaribMurshudov ***@***.***> wrote:
> 
> ﻿
> Has anybody tested this?
> 
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you authored the thread.

2025-02-11 15:48 UTC, GaribMurshudov commented
Have we addressed concerns raised by Keitaro? I guess @flong-mrc might need to look into this

2025-02-12 06:18 UTC, keitaroyam commented
OK, I manually removed the unnecessary torsion angle changes. We can merge this if you are happy with it. Acedrg may be updated later.

2025-02-14 12:33 UTC, GaribMurshudov approved these changes
I hope these were tested.

2025-02-14 12:34 UTC, keitaroyam approved these changes

2025-02-14 12:35 UTC, merged